### DISCUSSION TITLE
Pipeline issue after deleting record from source table

### DISCUSSION THREAD

**Discussion by Soumyabrata-Talapatra** [ConduitIO/conduit#2046] [Connectors]
I am using the builtin:postgres connector to replicate data from the source table to the destination table having one integer as primary key in source and destination table. However, if i delete any record from the source table then one error i am getting: 

2024-12-24T10:13:01+00:00 ERR node stopped error="node postgres_pipeline_41:postgres_source_41 stopped with error: source stream was stopped unexpectedly: error reading from source: read plugin error: failed to encode before payload: failed to marshal data with schema: could not marshal into avro: address: avro: *avro.null is unsupported for Avro string"

my pipeline yaml is:

```
version: 2.2

pipelines:
  - id: postgres_pipeline_41
    status: running
    name: postgres-pipeline_41
    description: Postgres pipeline configuration with column mapping
    connectors:
      - id: postgres_source_41
        type: source
        plugin: builtin:postgres
        name: my-postgres-source_41
        settings:
          url: "postgres://postgres:******@192.168.1.16:****/conduit_test_db?sslmode=disable"
          tables: "origin_table"
          cdcMode: "logrepl"
          logrepl.publicationName: "conduit_publication_41" # Choose a unique name
          logrepl.slotName: "conduit_slot_41" # Choose a unique name
               - id: postgres_dest_41
        type: destination
        plugin: builtin:postgres
        name: my-postgres-destination_41
        settings:
          url: "postgres://postgres:******@192.168.1.16:****/conduit_test_db?sslmode=disable"
          table: "destination_table"
    processors:
      - id: filter_id_ename_proc
        plugin: "postgres-processor_address_filter"
    dead-letter-queue:
        plugin: "builtin:file"    # use builtin file plugin as DLQ connector
        settings:
          path: "./dlq.out"       # route records to file ./dlq.out
        window-size: 10            # monitor last 10 records
        window-nack-threshold: 3  # tolerate up to 3 negatively acknowledged records
```

I have not used conduit much and my question may seem noobish. I would appreciate the help. Thanks in advance.
