### ISSUE TITLE
The pipelines.exit-on-error works inconsistently

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1179]
### Bug description

With the `pipelines.exit-on-error` specified via command line, Conduit _doesn't always_ exit. Roughly, once in 3-4 times it stops. It's interesting that when used in GoLand, it always works.

### Steps to reproduce

1. Build Conduit (latest, main, v0.7.1, v0.6.2)
2. Run with `./conduit -pipelines.exit-on-error -pipelines.path ./test.yaml`.

Expected: Conduit exits
Actual: Conduit sometimes exits

Test file: 
```yaml
version: "2.0"
pipelines:
    - id: file-pipeline
      status: running
      name: file-pipeline
      description: test pipline
      connectors:
        - id: source-connector
          type: source
          plugin: builtin:s3
          name: source-connector
          settings:
            path: ${SOURCE_FILE}
          processors: []
        - id: destination-connector
          type: destination
          plugin: builtin:s3
          name: destination-connector
          settings:
            path: ${DESTINATION_FILE}
          processors: []
      processors: []
      dead-letter-queue:
        plugin: ""
        settings: {}
        window-size: null
        window-nack-threshold: null
```

### Version

v0.8.0-nightly.20230817, v0.7.1, v0.6.2

**Comment by raulb** [comment]
@hariso yesterday at standup, we wondered whether this is still an issue.

**Comment by hariso** [comment]
I re-tested with the above pipeline and the pipeline below as well, and couldn't reproduce it.

```yaml
version: "2.2"
pipelines:
    - id: pipeline1
      status: running
      name: pipeline1
      description: generator source, chaos destination
      connectors:
        - id: source1
          type: source
          plugin: builtin:generator
          name: source1
          settings:
            collections.users.format.type: structured
            collections.users.format.options.id: int
            collections.users.format.options.name: string
            readTime: 10s
            recordCount: "5"
        - id: chaos-destination-1
          type: destination
          plugin: standalone:chaos
          name: chaos-destination-1
          settings:
            writeMode: error

```

Command:

```shell
rm -rf conduit.db/ && ./conduit run --pipelines.exit-on-degraded=true --pipelines.error-recovery.max-retries=3
```
