### ISSUE TITLE
MC: Support for dynamic configuration parameters in connectors

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#1487]
Add support for dynamic configuration parameters in connectors. Currently, parameters are statically defined in the connector specifications. Additionally, the SDK validates that the supplied configuration doesn't contain unused/unknown parameters. This prevents us from having dynamic parameter keys.

Implementing this would allow us to break up complex configuration fields into separate fields, for instance for the generator source:
```yaml
pipelines:
  - id: example
    connectors:
    - id: example
      plugin: generator
      settings:
        collections.foo.format.type: "file"
        collections.foo.format.options: "/path/to/file"
        collections.bar.format.type: "structured"
        collections.bar.format.options: "id:int,name:string"
```

Another example where we could benefit from this is the HTTP connector when defining custom headers:
```yaml
pipelines:
  - id: example
    connectors:
    - id: example
      plugin: http
      settings:
        headers.content-type: "application/json"
        headers.authorization: "basic ZGVtbzpwQDU1dzByZA=="
```

The same feature needs to be supported in conduit-commons and conduit-connector-sdk, as the connector SDK is not using types from the commons module yet.
