### ISSUE TITLE
HTTP Processor: change RawData into []byte

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#1497]
### Bug description

the processor response is saved as `RawData` even if it's under a `StructuredData` field.
investigate the problem, and change `RawData` into `[]byte` (should work for `.Payload.After` and other fields)

### Steps to reproduce

example pipeline config file:

```
version: 2.2
pipelines:
  - id: sfdc-to-webhook
    status: running
    description: >
      TBD.
    connectors:
      - id: employees-source
        type: source
        plugin: builtin:generator
        settings:
          format.type: "structured"
          format.options: "id:int,name:string,company:string,trial:bool"
          recordCount: "15"
          readTime: "1s"
      - id: webhook-sink
        type: destination
        plugin: standalone:http
        settings:
          url: "https://webhook.site/4fd2add3-db9f-4fe2-bf4d-c1cc88e60dff"
    processors:
      - id: fetch-pokemon-ditto
        plugin: "webhook.http"
        settings:
          backoffRetry.count: "0"
          backoffRetry.factor: "2"
          backoffRetry.max: "5s"
          backoffRetry.min: "100ms"
          request.body: ""
          request.contentType: "application/json"
          request.method: "GET"
          request.url: "https://pokeapi.co/api/v2/pokemon/ditto"
          response.body: ".Payload.After.response"
          response.status: ".Metadata[\"http_status\"]"
#      - id: decode-json
#        plugin: json.decode
#        settings:
#          field: ".Payload.After.response"

```
doesn't work without the json decoder processor.

### Version

latest
