### ISSUE TITLE
[Recovery] Make backoff parameters globally configurable

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#1782]
Add CLI flags, ENV variables and fields in `conduit.yaml` that allow you to configure the pipeline recovery default backoff values.

Here's an example of a `conduit.yaml` file with the default values:

```yaml
pipelines:
  error-recovery:
    min: 1s           # minimum delay is 1 second
    max: 10m          # maximum delay is 10 minutes
    factor: 2         # every retry we multiply the last delay by 2
    retries: 0        # infinite retries
    healthy-after: 5m # pipeline is considered healthy after 5 minutes of running without errors
```
