### ISSUE TITLE
Some fields are lost when a `field.set` processor is used

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1941]
### Bug description

When the `field.set` processor is used, then some fields can be lost, like in the pipeline below that uses a generator source, `field.set` to add a new field, and a file destination.

When the `field.set` processor is **not** present, then the generated records have the fields as expected.

### Steps to reproduce

1. Run Conduit with this pipeline:
```yaml
version: "2.2"
pipelines:
  - id: example-pipeline
    status: running
    name: "generator-to-file"
    connectors:
      - id: example-source
        type: source
        plugin: "generator"
        settings:
          format.options.airline: 'string'
          format.options.scheduledDeparture: 'time'
          format.type: 'structured'
          rate: 1
      - id: example-destination
        type: destination
        plugin: "file"
        settings:
          path: './destination.txt'
```

2. Check contents of `destination.txt` with `tail -f destination.txt | jq`. All the records will look similar to this:

```json
{
      "airline": "demicanon",
      "scheduledDeparture": "2024-11-05T13:57:19.436001Z"
}
```

3. Stop Conduit, change the pipeline include a `field.set` processor, like below:

```yaml
version: "2.2"
pipelines:
  - id: example-pipeline
    status: running
    name: "generator-to-file"
    processors:
      - id: add-city
        plugin: "field.set"
        settings:
          field: ".Payload.After.city"
          value: "Bedrock"
    connectors:
      - id: example-source
        type: source
        plugin: "generator"
        settings:
          format.options.airline: 'string'
          format.options.scheduledDeparture: 'time'
          format.type: 'structured'
          rate: 1
      - id: example-destination
        type: destination
        plugin: "file"
        settings:
          path: './destination.txt'

```

4. Run Conduit. Check contents of `destination.txt` with `tail -f destination.txt | jq`. All the records will look similar to this:

```json
{
      "airline": "rhombogenous",
      "scheduledDeparture": "1970-01-01T00:00:00.000007Z"
    }
```

**Expected result**:

Field `scheduledDeparture` has a non-zero value, `city` is present and set to `Bedrock`.

**Actual result**:

Field `scheduledDeparture` has a zero value, `city` is not present.

### Version

Commit 4c3c3751
