### ISSUE TITLE
Bug: Pipeline status `stopped` in a configuration file still runs the pipeline

### ISSUE THREAD

**Issue by raulb** [ConduitIO/conduit#2061]
### Bug description

This pipeline with the status `stopped` shouldn't run:

```yaml
version: "2.2"
pipelines:
  - id: example-pipeline
    status: stopped
    name: "test"
    connectors:
      - id: example-source
        type: source
        plugin: "generator"
        settings:
          # Generate field 'airline' of type string
          # Type: string
          # Optional
          format.options.airline: 'string'
          # Generate field 'scheduledDeparture' of type 'time'
          # Type: string
          # Optional
          format.options.scheduledDeparture: 'time'
          # The format of the generated payload data (raw, structured, file).
          # Type: string
          # Optional
          format.type: 'structured'
          # The maximum rate in records per second, at which records are
          # generated (0 means no rate limit).
          # Type: float
          # Optional
          rate: '1'
      - id: example-destination
        type: destination
        plugin: "file"
        settings:
          # Path is the file path used by the connector to read/write records.
          # Type: string
          # Optional
          path: './destination.txt'
```

This used to work so it seems there's been a regression.

### Steps to reproduce

1. Use the configuration pipeline that's above.
2. Run conduit `$ conduit run`
3. Notice this pipeline runs (it shouldn't).

### Version

v0.13.0-nightly.20250109
