### ISSUE TITLE
Bug: Provisioning of multiple pipelines in a yaml file fails if one of them has an invalid version

### ISSUE THREAD

**Issue by nickchomey** [ConduitIO/conduit#2255]
### Bug description

I was exploring how the multiple pipelines per yaml config worked and was trying to make it fail on one of them. 

When one has an invalid version, the whole provisioning fails with an error like `ERR provisioning failed error="could not parse file \"/home/nick/conduittest/pipelines/test.yaml\": parsing error: unrecognized version 4"`

Conversely, if you omit the connectors section from a pipeline, the others will provision and start and you just get this error `ERR provisioning failed error="pipeline \"yaml-test-pipeline-3\", error while provisioning: could not start the pipeline \"yaml-test-pipeline-3\": could not build nodes for pipeline yaml-test-pipeline-3: can't build pipeline without any source connectors"` for the bad pipeline. 

### Steps to reproduce

You could try using a config like this

```
---
version: 2.2
pipelines:
  - id: yaml-test-pipeline-1
    description: First pipeline created via YAML API
    connectors:
      - id: test-source-1
        type: source
        plugin: builtin:file
        settings:
          path: ./example.in
      - id: test-destination-1
        type: destination
        plugin: builtin:file
        settings:
          path: ./example-yaml-1.out
    processors: []
---
version: 2.2
pipelines:
  - id: yaml-test-pipeline-2
    description: Second pipeline created via YAML API
    connectors:
      - id: test-source-2
        type: source
        plugin: builtin:file
        settings:
          path: ./example.in
      - id: test-destination-2
        type: destination
        plugin: builtin:file
        settings:
          path: ./example-yaml-2.out
    processors: []
---
version: 4
pipelines:
  - id: yaml-test-pipeline-3
    description: Malformed pipeline with invalid version
    connectors:
      - id: test-source-3
        type: source
        plugin: builtin:file
        settings:
          path: ./example.in
      - id: test-destination-3
        type: destination
        plugin: builtin:file
        settings:
          path: ./example-yaml-3.out
    processors: []
```

### Version

0.13.4
