### ISSUE TITLE
Add CI action for generated code

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#45]
We should add a Github action that runs `make generate` and succeeds if there is no diff. It should run on each push to a PR.

~We could do the same with proto files (generate them and make sure there's no diff).~ Proto files aren't generated in the repo anymore, we use Buf remote code generation now.

**Comment by lovromazgon** [comment]
Note to assignee - that's the solution, just needs to be pasted into the action 😄 Thanks @lyuboxa ❤️ 
```
  gentest:
    name: Generated files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Generated files
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make generate
          git diff --exit-code --numstat
```
