### ISSUE TITLE
Pipeline stuck in running state with very fast source and a failing destination

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#662]
### Bug description

This bug was originally reported by @lyuboxa. He reported a problem with a pipeline with:
* a Kafka source with a topic with a very large number of messages, and 
* a Kafka destination with a topic which actually doesn't exist.

The logs show:
```
2022-10-06T17:22:20+00:00 ERR error writing record error="failed to produce messages: [3] Unknown Topic Or Partition: the request is for a topic or partition that does not exist on this broker" connector_id=pipeline1:destination1 plugin_name=builtin:kafka plugin_type=destination record_position=74571ce2-52b4-436e-8a4d-4ed8c92906e7
```
The pipeline, however, is in a running state.

When trying to stop it, we get:
```
{
    "code": 13,
    "details": [],
    "message": "failed to stop pipeline: tried to inject control message but PubNode is not running"
}
```

This issue can be reproduced with a very fast generator source and a Kafka destination which is failing. In the example below, the failure comes from the destination topic not existing, and the Kafka broker not allowing auto-create of topics.

### Steps to reproduce

```yaml
---
version: 1.0
pipelines:
  pipeline1:
    status: running
    name: pipeline1
    description: 'Fast generator source, Kafka destination'
    connectors:
      source1:
        type: source
        plugin: builtin:generator
        name: generator-source
        settings:
          recordCount: "-1"
          readTime: "0ms"
          format.options: "id:int,name:string,company:string,trial:bool"
          format.type: "structured"
      destination1:
        type: destination
        plugin: "builtin:kafka"
        name: kafka-destination
        settings:
          servers: "localhost:9092"
          topic: "non-existing-topic"

```

### Version

v0.4.0-nightly.20221006
