### ISSUE TITLE
Possible concurrency issues with shallow record copies

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#748]
### Bug description

Destination connectors mutate a record's metadata after they receive it. This can cause issues with the stream inspector (see [this comment](https://github.com/ConduitIO/conduit/pull/718#discussion_r1024054550)) or in pipelines with multiple destinations (see [this comment](https://github.com/ConduitIO/conduit/pull/718#discussion_r1028437875)).

### Steps to reproduce

TBD

### Version

v0.4.0-nightly.20221122

**Comment by hariso** [comment]
Here's a pipeline which reproduces the same issue, but with built-in connectors:
```yaml
---
version: 1.0
pipelines:
  pipeline1:
    status: running
    name: pipeline1
    description: 'generator source, two file destination'
    connectors:
      source1:
        type: source
        plugin: builtin:generator
        name: source1
        settings:
          recordCount: "1000"
          readTime: "0s"
          format.options: "id:int"
          format.type: "structured"
      file-destination-1:
        type: destination
        plugin: "builtin:file"
        name: file-destination-1
        settings:
          path: /tmp/file-destination-1.txt
      file-destination-2:
        type: destination
        plugin: "builtin:file"
        name: file-destination-2
        settings:
          path: /tmp/file-destination-2.txt
```
