### ISSUE TITLE
Bug: Fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by maksenius** [ConduitIO/conduit#795]
### Bug description

I created pipeline with 1 source connector it was sql server and 7 destinations connectors it were files connectors.  I started pipeline and got panic error
concurrent map iteration and map write

### Steps to reproduce

1. Create pipeline 1 source connector and 7 files destination connectors , for example
```yaml
pipelines:
  pipeline77:
    status: stopped
    name: file tests
    description: desc
    connectors:
      connect1:
        type: source
        plugin: sql-server
        name: sql server source
        settings:
          connection: "sqlserver://sa:password@0.0.0.0?database=mytest&connection+timeout=30"
          table: demo
          primaryKey: ID
          orderingColumn: ID
      connect2:
        type: destination
        plugin: file
        name: file1
        settings:
          path: /home/maksymsitarchuk/Documents/meroxa/files/file1.txt
      connect3:
        type: destination
        plugin: file
        name: file2
        settings:
          path: /home/maksymsitarchuk/Documents/meroxa/files/file2.txt
      connect4:
        type: destination
        plugin: file
        name: file3
        settings:
          path: /home/maksymsitarchuk/Documents/meroxa/files/file3.txt
      connect5:
        type: destination
        plugin: file
        name: file4
        settings:
          path: /home/maksymsitarchuk/Documents/meroxa/files/file4.txt
      connect6:
        type: destination
        plugin: file
        name: file5
        settings:
          path: /home/maksymsitarchuk/Documents/meroxa/files/file5.txt
      connect7:
        type: destination
        plugin: file
        name: file6
        settings:
          path: /home/maksymsitarchuk/Documents/meroxa/files/file6.txt
      connect8:
        type: destination
        plugin: file
        name: file7
        settings:
          path: /home/maksymsitarchuk/Documents/meroxa/files/file7.txt

```
2. Start pipeline
3. Get error
```
2022-12-23T17:51:04+00:00 WRN plugin configured with a nil SecureConfig component=plugin connector_id=pipeline77:connect1
2022-12-23T17:51:04+00:00 DBG starting destination connector plugin component=connector.Destination connector_id=pipeline77:connect5
2022-12-23T17:51:04+00:00 DBG configuring destination connector plugin component=connector.Destination connector_id=pipeline77:connect5
2022-12-23T17:51:04+00:00 INF destination connector plugin successfully started component=connector.Destination connector_id=pipeline77:connect5
2022-12-23T17:51:04+00:00 DBG starting destination connector plugin component=connector.Destination connector_id=pipeline77-dlq
2022-12-23T17:51:04+00:00 DBG starting plugin args=["/home/maksymsitarchuk/go/src/github.com/conduitio/conduit/connectors/sql-server"] component=plugin connector_id=pipeline77:connect1 path=/home/maksymsitarchuk/go/src/github.com/conduitio/conduit/connectors/sql-server
2022-12-23T17:51:04+00:00 DBG configuring destination connector plugin component=connector.Destination connector_id=pipeline77-dlq
2022-12-23T17:51:04+00:00 INF destination connector plugin successfully started component=connector.Destination connector_id=pipeline77-dlq
2022-12-23T17:51:04+00:00 INF destination connector plugin successfully started component=connector.Destination connector_id=pipeline77:connect6
2022-12-23T17:51:04+00:00 INF destination connector plugin successfully started component=connector.Destination connector_id=pipeline77:connect4
2022-12-23T17:51:04+00:00 DBG plugin started component=plugin connector_id=pipeline77:connect1 path=/home/maksymsitarchuk/go/src/github.com/conduitio/conduit/connectors/sql-server pid=121854
2022-12-23T17:51:04+00:00 DBG waiting for RPC address component=plugin connector_id=pipeline77:connect1 path=/home/maksymsitarchuk/go/src/github.com/conduitio/conduit/connectors/sql-server
2022-12-23T17:51:04+00:00 INF request processed duration=0.004017 grpc_method=/api.v1.PipelineService/GetPipeline grpc_status_code=OK http_endpoint="GET /v1/pipelines/pipeline77" request_id=57237632-a0a0-4648-a6f8-8c32f010f31b
2022-12-23T17:51:04+00:00 DBG plugin address address=/tmp/plugin100562303 component=plugin connector_id=pipeline77:connect1 network=unix plugin_name=sql-server
2022-12-23T17:51:04+00:00 DBG using plugin component=plugin connector_id=pipeline77:connect1 version=1
2022-12-23T17:51:04+00:00 DBG configuring source connector plugin component=connector.Source connector_id=pipeline77:connect1
2022-12-23T17:51:04+00:00 INF source connector plugin successfully started component=connector.Source connector_id=pipeline77:connect1
fatal error: concurrent map iteration and map write

goroutine 387 [running]:
runtime.throw({0x16e2f25?, 0xc000600000?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00690d1d0 sp=0xc00690d1a0 pc=0x439731
runtime.mapiternext(0x14370e0?)
        /usr/local/go/src/runtime/map.go:871 +0x4eb fp=0xc00690d240 sp=0xc00690d1d0 pc=0x41212b
reflect.mapiternext(0x4c1d8f?)
        /usr/local/go/src/runtime/map.go:1378 +0x19 fp=0xc00690d258 sp=0xc00690d240 pc=0x463ab9
reflect.(*MapIter).Next(0xc005e13a00?)
        /usr/local/go/src/reflect/value.go:1789 +0x7e fp=0xc00690d288 sp=0xc00690d258 pc=0x4c1fbe
encoding/json.mapEncoder.encode({0x2ae5220?}, 0xc000500700, {0x16526e0?, 0xc006299340?, 0xc00004ebb0?}, {0xb?, 0x0?})
        /usr/local/go/src/encoding/json/encode.go:799 +0x2d4 fp=0xc00690d448 sp=0xc00690d288 pc=0x56bff4
encoding/json.mapEncoder.encode-fm(0x160cbe0?, {0x16526e0?, 0xc006299340?, 0x47275d?}, {0xa0?, 0x72?})
        <autogenerated>:1 +0x45 fp=0xc00690d488 sp=0xc00690d448 pc=0x5766e5
encoding/json.structEncoder.encode({{{0xc0005f0900?, 0x0?, 0x0?}, 0xc0062e39e0?}}, 0xc000500700, {0x160cbe0?, 0xc006299320?, 0xc00690d5a8?}, {0x0, 0x1})
        /usr/local/go/src/encoding/json/encode.go:761 +0x1f4 fp=0xc00690d538 sp=0xc00690d488 pc=0x56ba74
encoding/json.structEncoder.encode-fm(0x160cbe0?, {0x160cbe0?, 0xc006299320?, 0xc00690d6e8?}, {0x4f?, 0xb8?})
        <autogenerated>:1 +0x69 fp=0xc00690d590 sp=0xc00690d538 pc=0x576629
encoding/json.(*encodeState).reflectValue(0xc00690d628?, {0x160cbe0?, 0xc006299320?, 0xc00690d680?}, {0x0?, 0x93?})
        /usr/local/go/src/encoding/json/encode.go:360 +0x78 fp=0xc00690d5f0 sp=0xc00690d590 pc=0x5695f8
encoding/json.(*encodeState).marshal(0xc006299320?, {0x160cbe0?, 0xc006299320?}, {0xb8?, 0xd6?})
        /usr/local/go/src/encoding/json/encode.go:332 +0xfa fp=0xc00690d668 sp=0xc00690d5f0 pc=0x56923a
encoding/json.Marshal({0x160cbe0, 0xc006299320})
        /usr/local/go/src/encoding/json/encode.go:161 +0x45 fp=0xc00690d6c8 sp=0xc00690d668 pc=0x5688c5
github.com/conduitio/conduit-connector-sdk.Record.Bytes({{0xc0005b8980, 0x7f, 0x80}, 0x4, 0xc0062e2f60, {0x2d2bde0, 0xc0062e2ff0}, {{0x2d2bdb8, 0x38998e0}, {0x2d2bdb8, ...}}})
        /home/maksymsitarchuk/go/pkg/mod/github.com/conduitio/conduit-connector-sdk@v0.4.0/record.go:122 +0x177 fp=0xc00690d7f0 sp=0xc00690d6c8 pc=0xca1957
github.com/conduitio/conduit-connector-file.(*Destination).Write(0xc0065a2d80, {0x0?, 0x80?}, {0xc0062992c0?, 0x1, 0x58?})
        /home/maksymsitarchuk/go/pkg/mod/github.com/conduitio/conduit-connector-file@v0.3.0/destination.go:72 +0x1e5 fp=0xc00690d900 sp=0xc00690d7f0 pc=0xcafa65
github.com/conduitio/conduit-connector-sdk.(*destinationWithRateLimit).Write(0xc000600000?, {0x2d30ec8?, 0xc0065c8060?}, {0xc0062992c0?, 0xc00690d998?, 0x40fa87?})
        /home/maksymsitarchuk/go/pkg/mod/github.com/conduitio/conduit-connector-sdk@v0.4.0/destination_middleware.go:237 +0xdb fp=0xc00690d950 sp=0xc00690d900 pc=0xca04db
github.com/conduitio/conduit-connector-sdk.(*writeStrategySingle).Write(0xc0065ab170, {0x2d30ec8, 0xc0065c8060}, {{0xc0005b8980, 0x7f, 0x80}, 0x4, 0xc0062e2f60, {0x2d2bde0, 0xc0062e2ff0}, ...}, ...)
        /home/maksymsitarchuk/go/pkg/mod/github.com/conduitio/conduit-connector-sdk@v0.4.0/destination.go:294 +0xc7 fp=0xc00690d9a8 sp=0xc00690d950 pc=0xc9f9e7
github.com/conduitio/conduit-connector-sdk.(*destinationPluginAdapter).Run(0xc0065a9dd0, {0x2d30ec8, 0xc0065c8060}, {0x2d2a0d0?, 0xc0065a2e80})
        /home/maksymsitarchuk/go/pkg/mod/github.com/conduitio/conduit-connector-sdk@v0.4.0/destination.go:189 +0x2d6 fp=0xc00690dbb0 sp=0xc00690d9a8 pc=0xc9eef6
github.com/conduitio/conduit-connector-protocol/cpluginv1.DestinationPlugin.Run-fm({0x2d30ec8?, 0xc0065c8060?}, {0x2d2a0d0?, 0xc0065a2e80?})
        <autogenerated>:1 +0x4f fp=0xc00690dbe8 sp=0xc00690dbb0 pc=0x11264ef
github.com/conduitio/conduit/pkg/plugin/builtin/v1.runSandboxNoResp[...].func1({0x2d2a0d0?, 0xc0065a2e80?})
        /home/maksymsitarchuk/go/src/github.com/conduitio/conduit/pkg/plugin/builtin/v1/sandbox.go:50 +0x31 fp=0xc00690dc18 sp=0xc00690dbe8 pc=0x1123cb1
github.com/conduitio/conduit/pkg/plugin/builtin/v1.runSandbox[...](0x58dd7f?, {0x2d30ec8?, 0xc0065c8060?}, {0x2d2a0d0?, 0xc0065a2e80?})
        /home/maksymsitarchuk/go/src/github.com/conduitio/conduit/pkg/plugin/builtin/v1/sandbox.go:41 +0xa3 fp=0xc00690dc90 sp=0xc00690dc18 pc=0x11259c3
github.com/conduitio/conduit/pkg/plugin/builtin/v1.runSandboxNoResp[...](0xc000495120?, {0x2d30ec8?, 0xc0065c8060?}, {0x2d2a0d0?, 0xc0065a2e80?})
        /home/maksymsitarchuk/go/src/github.com/conduitio/conduit/pkg/plugin/builtin/v1/sandbox.go:49 +0x5e fp=0xc00690dce8 sp=0xc00690dc90 pc=0x11258be
github.com/conduitio/conduit/pkg/plugin/builtin/v1.(*destinationPluginAdapter).Start.func1()
        /home/maksymsitarchuk/go/src/github.com/conduitio/conduit/pkg/plugin/builtin/v1/destination.go:92 +0x1b8 fp=0xc00690dfe0 sp=0xc00690dce8 pc=0x1120c78
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00690dfe8 sp=0xc00690dfe0 pc=0x46a161
created by github.com/conduitio/conduit/pkg/plugin/builtin/v1.(*destinationPluginAdapter).Start
        /home/maksymsitarchuk/go/src/github.com/conduitio/conduit/pkg/plugin/builtin/v1/destination.go:90 +0x335

goroutine 1 [chan receive]:
github.com/conduitio/conduit/pkg/conduit.(*Runtime).Run.func1()
        /home/maksymsitarchuk/go/src/github.com/conduitio/conduit/pkg/conduit/runtime.go:207 +0x98
github.com/conduitio/conduit/pkg/conduit.(*Runtime).Run(0xc00017c600, {0x2d30e20?, 0xc0001faf80?})
        /home/maksymsitarchuk/go/src/github.com/conduitio/conduit/pkg/conduit/runtime.go:265 +0xaa3
main.main()
        /home/maksymsitarchuk/go/src/github.com/conduitio/conduit/cmd/conduit/main.go:47 +0x1b8

goroutine 8 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc000094480?)
        /home/maksymsitarchuk/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
        /home/maksymsitarchuk/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf

goroutine 13 [select]:
github.com/dgraph-io/badger/v3/y.(*WaterMark).process(0xc00032d800, 0xc00032d7d0)
        /home/maksymsitarchuk/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.5/y/watermark.go:214 +0x285
created by github.com/dgraph-io/badger/v3/y.(*WaterMark).Init
        /home/maksymsitarchuk/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.5/y/watermark.go:72 +0xaa

goroutine 14 [select]:
github.com/dgraph-io/badger/v3/y.(*WaterMark).process(0xc00032da40, 0xc00032d7d0)
        /home/maksymsitarchuk/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.5/y/watermark.go:214 +0x285
created by github.com/dgraph-io/badger/v3/y.(*WaterMark).Init
        /home/maksymsitarchuk/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.5/y/watermark.go:72 +0xaa

goroutine 15 [select]:
github.com/dgraph-io/ristretto/z.(*AllocatorPool).freeupAllocators(0xc000424360)
        /home/maksymsitarchuk/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1/z/allocator.go:385 +0x150
created by github.com/dgraph-io/ristretto/z.NewAllocatorPool
        /home/maksymsitarchuk/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1/z/allocator.go:324 +0xc5

goroutine 16 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00049d700)
```

### Version

v0.5.0-nightly.20221217-dirty linux/amd64

**Comment by uchennakevinm1** [comment]
this happens becuase of shallow copy, we need to use deep copy.

**Comment by hariso** [comment]
Here's a pipeline which reproduces the same issue, but with built-in connectors:
```yaml
---
version: 1.0
pipelines:
  pipeline1:
    status: running
    name: pipeline1
    description: 'generator source, two file destination'
    connectors:
      source1:
        type: source
        plugin: builtin:generator
        name: source1
        settings:
          recordCount: "1000"
          readTime: "0s"
          format.options: "id:int"
          format.type: "structured"
      file-destination-1:
        type: destination
        plugin: "builtin:file"
        name: file-destination-1
        settings:
          path: /tmp/file-destination-1.txt
      file-destination-2:
        type: destination
        plugin: "builtin:file"
        name: file-destination-2
        settings:
          path: /tmp/file-destination-2.txt
```
