### ISSUE TITLE
Teradata RDBMS connector

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#863]
Write java-based Teradata connector(s) for conduit using [Java Database Connectivity (JDBC) API](https://www.oracle.com/technetwork/java/javase/jdbc/index.html).

**Comment by hariso** [comment]
The quickest way to do it is using Conduit's [Kafka Connect Wrapper](https://github.com/ConduitIO/conduit-kafka-connect-wrapper). Following is needed:
1. Download [Teradata's JDBC driver](https://repo1.maven.org/maven2/com/teradata/jdbc/terajdbc/17.20.00.15/terajdbc-17.20.00.15.jar) and put into the wrapper's `libs` directory.
2. Example configuration:
```yaml
---
version: 1.0
pipelines:
  pipeline1:
    status: running
    name: pipeline1
    description: 'Teradata source, file destination'
    connectors:
      teradata-source:
        type: source
        plugin: "standalone:conduit-kafka-connect-wrapper@v0.3.0"
        name: teradata-source
        settings:
          wrapper.connector.class:  "io.aiven.connect.jdbc.JdbcSourceConnector"
          connection.url:           "jdbc:teradata://192.168.1.10"
          connection.user:          "dbc"
          connection.password:      "dbc"
          tables:                   "HR.Employees"
          topic.prefix:             "foobar_"
          mode:                     "incrementing"
          incrementing.column.name: "id"

      file-destination:
        type: destination
        plugin: "builtin:file"
        name: file-destination
        settings:
          path: /tmp/file-destination.txt

```
